### ISSUE TITLE
Cross-field validation not working

### ISSUE THREAD

**Issue by DanielSWolf** [formstate/formstate#11]
I often need validation rules that access more than just a single field. Typical examples are:

* 'Password' and 'Repeat password': The validation rule on 'Repeat password' should not only check that the field is not empty. It should *also* check that the value is identical to the value in 'Password'.
* 'Start time' and 'End time': The validation rule on 'End time' should not only check that 'End time' is a valid time. It should *also* check that 'End time' is greater than 'Start time'.

The important thing here is that these validators should not just be re-evaluated when the value of their own field changes. They also have to be re-evaluated when the value of another field that's used in the validator changes. For example, the validator on 'Repeat password' should run whenever 'Password' *or* 'Repeat password' is changed.

Luckily, MobX is great at tracking these kinds of dependencies, and it's my understanding that you use MobX internally. So I expected that I could simply access the values of other fields within a validator. MobX would then automatically detect that the validator for 'Repeat password' depends on the value of 'Password' and re-evaluate it accordingly.

For some reason, this doesn't seem to work. The validator on 'Repeat password' only gets re-evaluated when I change the value of 'Repeat password', not when I change the value of 'Password'.

Below is my demo code. I'm sure I must have made some small error, but I can't find it.

```js
import React, { Component } from 'react';
import { FormState, FieldState } from 'formstate';
import { observer } from 'mobx-react';

@observer
class Input extends Component {
  render() {
    const { fieldState, label } = this.props;
    return (
      <div>
        <p>{label}</p>
        <p style={{ color: 'orange' }}>{fieldState.error}</p>
        <input
          type="text"
          value={fieldState.value}
          onChange={args => fieldState.onChange(args.target.value)}
        />
      </div>
    );
  }
}

@observer
export default class Usecase extends Component {
  constructor(props) {
    super(props);
    this.formState = new FormState({
      userName: new FieldState({ value: '' })
        .validators(value => !value && 'User name is required.'),
      password: new FieldState({ value: '' })
        .validators(value => !value && 'Password is required.'),
      repeatPassword: new FieldState({ value: '' })
        .validators(value => {
          if (!value) return 'Repeated password is required.';
          return (value !== this.formState.$.password.$) && 'Repeated password must match password.';
        })
    });
  }

  componentWillMount() {
    this.formState.validate();
  }

  render(){
    return (
      <form>
        <Input fieldState={this.formState.$.userName} label="User name" />
        <Input fieldState={this.formState.$.password} label="Password" />
        <Input fieldState={this.formState.$.repeatPassword} label="Repeat password" />
      </form>
    );
  }
}
```

**Comment by basarat** [comment]
> Luckily, MobX is great at tracking these kinds of dependencies

Yes it does but I've intentionally tried not to use too much of mobx internals.

> They also have to be re-evaluated when the value of another field that's used in the validator changes. 

Instead of relying on mobx magic which I will have to keep updated as new versions of mobx come out I've chosen to move the *inter field* relationship to be explicit behind a `compose` function. I would rewrite your example to be explicit about the fields that depend on each other as follows: 

```ts
this.formState = new FormState({
      userName: new FieldState({ value: '' })
        .validators(value => !value && 'User name is required.'),
      pass: new FormState({
        password: new FieldState({ value: '' })
          .validators(value => !value && 'Password is required.'),
        repeatPassword: new FieldState({ value: '' })
          .validators(value => {
            if (!value) return 'Repeated password is required.';
          })
      })
       .compose()
       .validators($ => $.password.$ !== $.repeatPassword.$ && 'Names must match')
    });
```

`compose` is mentioned here : https://formstate.github.io/demos/#cross-field-validation

I am happy to consider an alternative API if you can think of how it would work internally :rose:

> 'Start time' and 'End time': The validation rule on 'End time' should not only check that 'End time' is a valid time. It should also check that 'End time' is greater than 'Start time'.

Here is some code from our public styleguide http://ap-react.s3-website-ap-southeast-2.amazonaws.com/#fields

```ts
new ap.FormState({
    startDate: new ap.FieldState({ value: '' }).validators(ap.validation.required, ap.validation.dateOnly),
    endDate: new ap.FieldState({ value: '' }).validators(ap.validation.required, ap.validation.dateOnly),
  }).compose().validators($ => {
    if (ap.moment($.startDate.$).isSameOrAfter(ap.moment($.endDate.$))) {
      return 'End date must be after start date';
    }
  })
```
Hope that helps :heart:

**Comment by oyvindberg** [comment]
So, I havent understood the whole codebase yet, but `compose()` stood out as unnecessary. Is there any reason why `validators` in `FormState` cannot just call `compose()` itself, if it's really needed?

**Comment by basarat** [comment]
> Is there any reason why validators in FormState cannot just call compose() itself, if it's really needed?

There are multiple ways to skin the cat. This was just what we choose. `compose` allows you to compose the fields without needing to store the reference to the formstate explicility.

**Comment by ghost** [comment]
@basarat 

Sorry to revive an old post, but this seems a relevant place to ask this, rather than creating a new and nearly identical issue. Thank you for your time, and I hope this is an appropriate place to ask this 🌹


The example [above](https://github.com/formstate/formstate/issues/11#issuecomment-279861705), and [in the documentation](https://formstate.github.io/#/?id=formstate-validators) shows multiple field validators (e.g. new password and confirm password must match) being implemented as "form level" validators.

(*"form level"/form state rather the more common "field level"/field state.)


From what I've learnt so far:

- form level validators only run on-demand (i.e. when the developer explicitly requests it `const result = await this.formState.validate();`)
- Form level validators only produce errors at the form level.


Or to rephrase it:

- The error will not appear as the user is typing and causes the issue, instead it will show up when the user clicks "Submit", or whenever else the dev decides to call validate on the form.
- The error will not disappear as the user is typing and corrects the issue, instead it will disappear when the user clicks "Submit", or whenever else the dev decides to call validate on the form.
- The error will be at the form level, rather than at the field level, and so the error message will appear for the form, and not the fields affected.

Is my understanding correct?

Moving on from that, I wondered if a validator could be made in to a MobX computed in some way. But looking at the typings, a validator must be either a plain function or a Promise.

If it was a computed, observing the values of both fields, then that'd work, and it'd only be called when those specific fields changed which would be great.

Seeing that promises can be used as a validation result, I had a quick think about using them somehow, but promises can only be resolved once, and so aren't applicable here to this particular issue.

Finally, I tried a jury-rigged solution involving [MobX autorun](https://mobx.js.org/refguide/autorun.html), and manually calling validate on the field.

```typescript
private newPasswordValue = "";

private passwordsMatchValidator = (confirmPasswordValue: string) => {
    return (confirmPasswordValue === this.newPasswordValue) ? undefined : "Passwords don't match.";
};

private formState = new FormState.FormState({
    currentPassword: new FormState.FieldState("").disableAutoValidation().validators(
        Validators.createRequired("Current Password"),
        Validators.createMinLength("Current Password", 8)
    ),
    newPassword: new FormState.FieldState("").disableAutoValidation().validators(
        Validators.createRequired("New Password"),
        Validators.createMinLength("New Password", 8)
    ),
    confirmNewPassword: new FormState.FieldState("").disableAutoValidation().validators(
        Validators.createRequired("Confirm New Password"),
        Validators.createMinLength("Confirm New Password", 8),
        this.passwordsMatchValidator
    )
});
    //.compose()
    //.validators(($) => newPasswordConfirmPasswordEqualValidator($.newPassword.$, $.confirmNewPassword));

public componentDidMount() {
    MobX.autorun(() => {
        this.newPasswordValue = this.formState.$.newPassword.value;
        //@ts-ignore Property is accessed so autorun can track the property. Value is not used.
        const confirmPasswordValue = this.formState.$.confirmNewPassword.value;

        //AJ: This would be better as this.formState.$.confirmNewPassword._autoValidationEnabled
        if (this.formState.$.confirmNewPassword.hasBeenValidated) {
            this.formState.$.confirmNewPassword.validate();
        }
    });
}
```

I don't like this approach as it feels like it's trying to work against form-state, rather than with it. I'm partially taking over control of when the validation is performed, and having to misuse the public API as important bits of information (`_autoValidationEnabled`) are internal.

It does however appear to work, including with [`disableAutoValidation`/`enableAutoValidationAndValidate`](https://formstate.github.io/demos/#validation-triggering). That said, I only spent a couple of minutes clicking around to test this prototype code, so it might not work when used for real.

Is there an approach I haven't read about yet, or not thought of?

I know you try to avoid adding too much reliance on MobX, and keeping that to a minimum makes sense to me, but would you be open to allowing computed (or similar) validators?

**Comment by ghost** [comment]
I tried to wrap that nastiness in to a utility function, so I could at least hide it away for now.
Unfortunately there doesn't seem to be a way to add a validator to a `FieldState` after construction.

Well, thats not entirely true, [`fieldState.Validators()`](https://github.com/formstate/formstate/blob/master/src/core/fieldState.ts#L71) would replace the current validators.
So I could use that, but since there's no way to get the existing validators, it'd mean all the validators would have to be assigned by the helper function, and none during construction.

Again, this is just fighting against form-state rather than working with it, further showing just how bad an option what I've come up with is.

```typescript
export const addAutorunValidator = <TFieldValue, TForm extends FormState.ValidatableMapOrArray>(
    fieldState: FormState.FieldState<TFieldValue>,
    formState: FormState.FormState<TForm>,
    validator: (fieldValue: TFieldValue, form: FormState.FormState<TForm>) => string | null | undefined,
    initValue: TFieldValue
) => {
    const fieldValidator: FormState.Validator<TFieldValue> = (fieldValue) => {
        return validator(fieldValue, formState);
    };

    const autorunDisposer = MobX.autorun(() => {
        validator(initValue, formState);

        //AJ: This would be better as fieldState._autoValidationEnabled
        if (fieldState.hasBeenValidated) {
            fieldState.validate();
        }
    });

    fieldState.validators(/* fieldState._validators.concat */ fieldValidator);

    return autorunDisposer;
};

const autorunDisposer = FormStateUtils.addAutorunValidator(
    this.formState.$.confirmNewPassword,
    this.formState,
    (fieldValue, formState) => (fieldValue === formState.$.newPassword.value) ? "" : "Must match 'New Password'.",
    "" //AJ: oh for default(TFieldValue)
);
```


EDIT:

A thought just occurred, that the fields in question are protected, meaning I could gain access to them via inheritance.

So rather than making some external helper functions, I could inherit from `FieldState` myself, and add this functionality to my own `CorruptedFieldState`.

That would solve many of the problems caused by trying to solve the problem this way. Although it'd not solve the root problem of not being able to do this without modifications to form-state.

**Comment by ghost** [comment]
I used inheritance to wrap up the functionality I've been playing with and to access the protected fields which make things work a little more correctly.

It's still a horrible hack, but I think it's finally to a point where I need to say "good enough" and move on.

```typescript
export class AutorunFieldState<TFieldValue> extends FormState.FieldState<TFieldValue> {
    constructor(initValue: TFieldValue) {
        super(initValue);
    }

    @MobX.action
    public addAutorunValidator = <TForm extends FormState.ValidatableMapOrArray>(
        formState: FormState.FormState<TForm>,
        validator: (fieldValue: TFieldValue, form: FormState.FormState<TForm>) => string | null | undefined,
        initValue: TFieldValue
    ) => {
        //AJ: Add a validator which takes a single value, wrapping our form state aware validator.
        this._validators.push((fieldValue) => validator(fieldValue, formState));

        const autorunDisposer = MobX.autorun(() => {
            //AJ: Run this every time, even though we do nothing with the output.
            //AJ: MobX tracks the observables used in the autorun, and not just on the first run.
            //AJ: Apparently it updates the observables watch list on every run.
            validator(initValue, formState);

            if (this._autoValidationEnabled) {
                //AJ: If we need to validate, then queue a validation.
                //AJ: This provides context sensitive validation and debouncing.
                this.queueValidation();
            }
        }, {
            name: "ValidatorAutorun"
        });

        return autorunDisposer;
    };
};

private formState = new FormState.FormState({
    currentPassword: new FormState.FieldState("").disableAutoValidation().validators(
        Validators.createRequired("Current Password"),
        Validators.createMinLength("Current Password", 8)
    ),
    newPassword: new FormState.FieldState("").disableAutoValidation().validators(
        Validators.createRequired("New Password"),
        Validators.createMinLength("New Password", 8)
    ),
    confirmNewPassword: new AutorunFieldState("").disableAutoValidation().validators(
        Validators.createRequired("Confirm New Password"),
        Validators.createMinLength("Confirm New Password", 8)
    )
});

private confirmNewPasswordDisposeAutorun: MobX.IReactionDisposer | undefined;

public componentDidMount() {
    const autorunFieldState = this.formState.$.confirmNewPassword as AutorunFieldState<string>;

    this.confirmNewPasswordDisposeAutorun = autorunFieldState.addAutorunValidator(
        this.formState,
        (fieldValue, formState) => {
            return (fieldValue === formState.$.newPassword.value) ? "" : "Must match 'New Password'.";
        },
        ""
    );
}

public componentWillUnmount() {
    if(this.confirmNewPasswordDisposeAutorun)
        this.confirmNewPasswordDisposeAutorun();
}
```

**Comment by basarat** [comment]
> form level validators only run on-demand (i.e. when the developer explicitly requests it const result = await this.formState.validate();)

No. If you call `formstate.compose`, they also run when *all the fields* are valid see : https://formstate.github.io/demos/#cross-field-validation

![image](https://user-images.githubusercontent.com/874898/40691941-2d192ee6-63f2-11e8-9962-7517f6e24b13.png)

Sorry for the late reply. Been a busy few days / weekend :heart:
