### ISSUE TITLE
FormState.compose and initial values

### ISSUE THREAD

**Issue by procedular** [formstate/formstate#22]
Hi again,
I like the idea behind the `compose` function of a `FormState`. It explains your concept of cross field validation by combining FormStates. :heart: So, i gave it a try and found some inconsistencies concerning the initial field values.

If the initial values are empty, as in your [cross field validation example](https://formstate.github.io/demos/#cross-field-validation), everything is fine. But when i pass a non-empty initial value, sometimes the form validation does not get triggered. Especially when the cross field validation was valid and should find an error on changing a value. Sadly, i am not sure why and when the auto validation of the form does not work.

A reproducible setup:
- take the [cross field validation example](https://formstate.github.io/demos/#cross-field-validation)
- change the initial values both to 'foo' or any other two equal strings
```
const form = new FormState({
  name1: new FieldState('foo').validators(nameRequired),
  name2: new FieldState('foo').validators(nameRequired),
})
```
- mount the example and note that every validation passes (as it should be)
- start changing one of the values
- **the validator does not get triggered and sets no form error**
- even on leaving the field (with a value that does not match the other field) nothing happens

**Comment by basarat** [comment]
This is the cause. In formstate, 

```
 /**
           * If no field has error
           * and all subfields are validated
           *  then re-validate the form */
          if (!this.hasFieldError
            && !this.getValues().some(value => this.validatedSubFields.indexOf(value) === -1)
          ) {
            this.validate();
          }
```
So if you start off as : 

![image](https://cloud.githubusercontent.com/assets/874898/23969974/6ef66cc4-0a1c-11e7-9d5a-82d8adb67371.png)

And only change the second field: 
![image](https://cloud.githubusercontent.com/assets/874898/23970008/8a8ab6c0-0a1c-11e7-8503-0fb4fdcd2dcb.png)

Since the *first* field has never been validated `compose` logic doesn't validate the whole form. 

Note that if you click `submit` it will still give you that error: 

![image](https://cloud.githubusercontent.com/assets/874898/23970062/bc1f6122-0a1c-11e7-919a-3958a9eccf5b.png)

Thinking of providing you a workaround :rose:

**Comment by basarat** [comment]
> Thinking of providing you a workaround 🌹

Workaround with `0.20.0` (untested but should work): 

```ts
class MyFormState<TValue> extends FormState<TValue>{
   assumeAllFieldsValid() {
     this.validatedSubFields = this.getValues();
     return this;
   }
}
```

Reason of not adding this function `assumeAllFieldsValid` to `FormState` proper: It is not a particularly easy function to document, but is exactly what is being requested here :rose:
